version: "3.8"

services:
  backend:
    build: .
    container_name: spring_backend
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5437/mini_proyect
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Johan123